// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// RealSense API
namespace realsense {

  dictionary Version {
    DOMString major;
    DOMString minor;
  };

  callback VersionPromise = void (Version version, DOMString error);

  interface Functions {
    static void getVersion(VersionPromise promise);

    [nodoc] static RealSense realSenseConstructor(DOMString objectId);
    [nodoc] static ScenePerception ScenePerceptionConstructor(DOMString objectId);
    [nodoc] static Scan3D Scan3DConstructor(DOMString objectId);
  };
};
